---

# not always installed (example: docker xenial)
- name: apt-transport-https
  package:
    name: apt-transport-https

- name: atom repository keys
  apt_key:
    data: "{{ lookup('file', 'atom.gpg') }}"
    state: present

- name: atom repository
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    state: present
    filename: atom
