---

- name: atom repository
  yum_repository:
    name: atom
    description: google-chrome
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch
    enabled: yes
    file: atom
    gpgcheck: no
    repo_gpgcheck: yes
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
