---

- name: atom rpm key
  copy:
    src: atom.gpg
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-ATOM
  register: atom_rpm_gpg

- name: atom repository
  yum_repository:
    name: atom
    description: atom
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch
    enabled: true
    file: atom
    gpgcheck: false
    repo_gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ATOM
  register: atom_rpm_repo

# force gpg key installation (needed on centos 7)
- name: install key
  shell: yum makecache -y --disablerepo='*' --enablerepo=atom
  args:
    # no warn about yum module usage
    warn: false
  when: |
    (atom_rpm_gpg.changed or atom_rpm_repo.changed)
    and ansible_distribution in ['CentOS', 'RedHat']
