---

- import_role:
    name: powo.rpmfusion
  when: ansible_os_family == 'RedHat'

- import_role:
    name: epel
  when: ansible_distribution in ['RedHat', 'CentOS']

- import_tasks: ppa-nextcloud.yml
  become: true
  become_user: root
  when: ansible_distribution == 'Ubuntu'

- import_tasks: atom-rpm.yml
  become: true
  become_user: root
  when: ansible_os_family == 'RedHat'

- import_tasks: atom-deb.yml
  become: true
  become_user: root
  when: ansible_os_family == 'Debian'

- name: privileged
  become: true
  become_user: root
  block:
    - name: misc
      package:
        name: "{{ _pmi_packages }}"

    - name: ssh
      service:
        name: "{{ _pmi_ssh_service }}"
        state: started
        enabled: true
