---

- name: privileged
  become: true
  become_user: root
  block:
    - name: misc
      with_items: "{{ _pmi_packages }}"
      package:
        name: "{{ item }}"

    - name: ssh
      service:
        name: "{{ _pmi_ssh_service }}"
        state: started
        enabled: true
